### ISSUE TITLE
Triangle Inequality not satisfied

### ISSUE THREAD

**Issue by brianpenghe** [arimorcos/Helper-Functions-Ari-Matlab#1]
I wanted to plot a special case of Venn where A=[a b] B=[b c] C=[a b c] so that A and B has intersects and both of them sit inside C.
But the program can't do it. 
Any recommendations?

**Comment by arimorcos** [comment]
Sorry, I didn't write the function, just got it from the file exchange here: https://uk.mathworks.com/matlabcentral/fileexchange/22282-venn?focused=5178911&tab=function

Perhaps try there.
